# Generated by Django 5.0.8 on 2026-06-13 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('checkup', 'Осмотр'), ('treatment', 'Лечение'), ('surgery', 'Операция'), ('lab', 'Анализы'), ('other', 'Прочее')], default='checkup', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('vet_name', models.CharField(blank=True, max_length=120)),
                ('clinic', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.animal')),
            ],
        ),
    ]
