# Generated by Django 5.0.8 on 2026-06-09 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActivityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('daily_score', models.PositiveSmallIntegerField(default=50)),
                ('metrics', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='animals.animal')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
