import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AdminProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('department', models.CharField(blank=True, max_length=120)),
                        ('notes', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='UserProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('phone', models.CharField(blank=True, max_length=32)),
                        ('avatar_url', models.URLField(blank=True)),
                        ('timezone', models.CharField(default='Asia/Bishkek', max_length=64)),
                        ('language', models.CharField(default='ru', max_length=8)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "accounts_adminprofile" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "department" varchar(120) NOT NULL DEFAULT '',
                            "notes" text NOT NULL DEFAULT '',
                            "created_at" timestamp with time zone NOT NULL,
                            "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE TABLE IF NOT EXISTS "accounts_userprofile" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "phone" varchar(32) NOT NULL DEFAULT '',
                            "avatar_url" varchar(200) NOT NULL DEFAULT '',
                            "timezone" varchar(64) NOT NULL DEFAULT 'Asia/Bishkek',
                            "language" varchar(8) NOT NULL DEFAULT 'ru',
                            "created_at" timestamp with time zone NOT NULL,
                            "updated_at" timestamp with time zone NOT NULL,
                            "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
                        );
                    """,
                    reverse_sql="""
                        DROP TABLE IF EXISTS "accounts_userprofile";
                        DROP TABLE IF EXISTS "accounts_adminprofile";
                    """,
                ),
            ],
        ),
    ]
