# Generated by Django 5.0.8 on 2026-06-09 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('imei', models.CharField(blank=True, max_length=40)),
                ('sim_iccid', models.CharField(blank=True, max_length=40)),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('blocked', 'Blocked'), ('unclaimed', 'Unclaimed')], default='unclaimed', max_length=24)),
                ('mode', models.CharField(choices=[('standby', 'Standby'), ('normal', 'Normal'), ('walk', 'Walk'), ('sos', 'SOS')], default='normal', max_length=24)),
                ('battery_level', models.PositiveSmallIntegerField(default=100)),
                ('signal', models.IntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('device_token_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='animals.animal')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='devices.device')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deviceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device',), name='one_active_assignment_per_device'),
        ),
    ]
